workspace:
  base: /woodpecker
  path: src/GITEA_HOST_REDACTED/${CI_REPO_OWNER}/${CI_REPO_NAME}

when:
  branch: test-woodpecker
  event: push

variables:
  REGISTRY: REGISTRY_REDACTED
  IMAGE_TAG: ${CI_COMMIT_SHA:0:7}
  COMPOSE_IMAGE_APP: news-aggregator-app
  COMPOSE_IMAGE_CADDY: news-aggregator-caddy

steps:
  - name: sync-to-github
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      GITHUB_REPO_URL:
        from_secret: github_repo_url
    commands:
      - |
        set -e # Exit immediately if a command exits with a non-zero status.

        REMOTE_URL=https://${GITHUB_TOKEN}@https://github.com/GITHUB_USER_REDACTED/news-aggregator.git

        echo "Mirroring repository..."
        git remote rm github 2>/dev/null || true
        git remote add github ${GITHUB_REPO_URL}
        git push github --all
        git push github --tags
        echo "Mirroring successful."

  - name: build-images-with-compose
    image: docker/compose:1.29.2
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose build

  - name: tag-and-push-images
    image: docker:20.10
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - "docker tag ${COMPOSE_IMAGE_APP}:latest ${REGISTRY}/${COMPOSE_IMAGE_APP}:${IMAGE_TAG}"
      - "docker tag ${COMPOSE_IMAGE_APP}:latest ${REGISTRY}/${COMPOSE_IMAGE_APP}:latest"
      - "docker push ${REGISTRY}/${COMPOSE_IMAGE_APP}:${IMAGE_TAG}"
      - "docker push ${REGISTRY}/${COMPOSE_IMAGE_APP}:latest"
      - "docker tag ${COMPOSE_IMAGE_CADDY}:latest ${REGISTRY}/${COMPOSE_IMAGE_CADDY}:${IMAGE_TAG}"
      - "docker tag ${COMPOSE_IMAGE_CADDY}:latest ${REGISTRY}/${COMPOSE_IMAGE_CADDY}:latest"
      - "docker push ${REGISTRY}/${COMPOSE_IMAGE_CADDY}:${IMAGE_TAG}"
      - "docker push ${REGISTRY}/${COMPOSE_IMAGE_CADDY}:latest"

