workspace:
  base: /woodpecker
  path: src/GITEA_HOST_REDACTED/${CI_REPO_OWNER}/${CI_REPO_NAME}

when:
  branch: test-woodpecker
  event: push

variables:
  REGISTRY: REGISTRY_REDACTED
  IMAGE_TAG: ${CI_COMMIT_SHA:0:7}
  COMPOSE_IMAGE_APP: news-aggregator-app
  COMPOSE_IMAGE_CADDY: news-aggregator-caddy

steps:
  - name: sync-to-github
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      GITHUB_REPO_URL:
        from_secret: github_repo_url
    commands:
      - '[ -z "$GITHUB_TOKEN" ] && echo "Error: GITHUB_TOKEN secret is not set." && exit 1'
      - '[ -z "$GITHUB_REPO_URL" ] && echo "Error: GITHUB_REPO_URL secret is not set." && exit 1'
      - git remote rm github 2>/dev/null || true
      - git remote add github "https://${GITHUB_TOKEN}@${GITHUB_REPO_URL#https://}"
      - git remote -v
      - git push github --all
      - git push github --tags

  - name: build-images-with-compose
    image: docker/compose:1.29.2
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose build

  - name: tag-and-push-images
    image: docker:20.10
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - "docker tag ${COMPOSE_IMAGE_APP}:latest ${REGISTRY}/${COMPOSE_IMAGE_APP}:${IMAGE_TAG}"
      - "docker tag ${COMPOSE_IMAGE_APP}:latest ${REGISTRY}/${COMPOSE_IMAGE_APP}:latest"
      - "docker push ${REGISTRY}/${COMPOSE_IMAGE_APP}:${IMAGE_TAG}"
      - "docker push ${REGISTRY}/${COMPOSE_IMAGE_APP}:latest"
      - "docker tag ${COMPOSE_IMAGE_CADDY}:latest ${REGISTRY}/${COMPOSE_IMAGE_CADDY}:${IMAGE_TAG}"
      - "docker tag ${COMPOSE_IMAGE_CADDY}:latest ${REGISTRY}/${COMPOSE_IMAGE_CADDY}:latest"
      - "docker push ${REGISTRY}/${COMPOSE_IMAGE_CADDY}:${IMAGE_TAG}"
      - "docker push ${REGISTRY}/${COMPOSE_IMAGE_CADDY}:latest"
